experiment:
  name: vehicle

data:
  input: .experiments/vehicle/
  process:
    processes:
      - name: rename
      - name: resize
        params:
          - 640
    processor: linear
  
dataset:
  balance: false
  classes:
    - ambulance
    - bicycle
    - Bus
    - Jeepney
    - Motorcycle
    - Multicab
    - Pickup
    - SUV
    - Sedan
    - Truck
    - Van
  framework: ultralytics
  input: .experiments/vehicle/storage
  path: .experiments/vehicle/dataset
  split: # test, train, valid
    - 0.2
    - 0.6
    - 0.2
  task: detect

model:
  architecture: fastsam
  framework: ultralytics
  path: hub/models/FastSAM-s.pt
  task: detect
  weights: 

storage: .experiments/vehicle/storage