data:
  input: .pipeline/vehicle/images
  process:
    processes:
      - name: rename
      - name: resize
        params:
          - 640
    processor: linear
dataset:
  balance: false
  classes:
    - ambulance
    - bicycle
    - Bus
    - Jeepney
    - Motorcycle
    - Multicab
    - Pickup
    - SUV
    - Sedan
    - Truck
    - Van
  framework: ultralytics
  input: .pipeline/vehicle/storage
  output: .pipeline/vehicle/dataset
  split: # test, train, valid
    - 0.2
    - 0.6
    - 0.2
  task: detect
model:
  architecture: yolo
  framework: ultralytics
  input: .pipeline/vehicle/models/train/weights/best.pt
  output: .pipeline/vehicle/models
  task: detect
  weights:
  prediction:
    config: configs/prediction.yaml
    top5: false # applied only for classification results
  train:
    config: configs/train.yaml
    data: .pipeline/vehicle/dataset/data.yaml
  validation:
    config: configs/validation.yaml
    data: .pipeline/vehicle/dataset/data.yaml
