
framework:
  name: ultralytics

data:
  input: .experiments/vehicle/database.csv
  process:
    processes:
      - name: crop
      - name: rename
      - name: resize
        params:
          - 640
    processor: linear


model:
  architecture: fastsam
  framework: ultralytics
  path: hub/models/FastSAM-s.pt
  weights:  